package ait.a00231910.microservices.controllers;

import static org.mockito.ArgumentMatchers.any;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.client.match.MockRestRequestMatchers.content;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import java.util.Optional;

import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import org.mockito.Captor;
import org.mockito.internal.verification.Times;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;

import com.fasterxml.jackson.databind.ObjectMapper;

import ait.a00231910.microservices.dao.ProductRepository;
import ait.a00231910.microservices.dto.Product;
import ait.a00231910.microservices.services.ProductService;

@SpringBootTest
@AutoConfigureMockMvc
class ProductControllerMockMVCTest {
	
	@Autowired
	ProductController productController;
	
	@MockBean
	ProductRepository productRepo;
	
	@MockBean
	ProductService productService;
	
	@Captor
	ArgumentCaptor<Product> captor;
	
	@Autowired
	private MockMvc mockMvc;
	
	/**
	 * Returns 'Hello World' from the root URI
	 * @throws Exception
	 */
	@Test
	public void getHelloTest() throws Exception
	{
		// Generate the result of a Get request on the root URI
		MvcResult result = this.mockMvc.perform(get("/")).andDo(print()).andExpect(status().isOk()).andReturn();
		
		// Specify the expected output
		String expected = "Hello World";
		
		// Compare the expected with the actual output
		assertEquals(expected, result.getResponse().getContentAsString());
	}
	
	@Test
	public void addProductControllerTest() throws Exception
	{
		// Building a product object
		Product product = buildProduct();
		
		// Getting a String representation of the product
		ObjectMapper map =new ObjectMapper();
		String jsonString = map.writeValueAsString(product);

		// The result is generated by performing a post request on the relevant endpoint
		this.mockMvc.perform(post("/products").contentType(MediaType.APPLICATION_JSON)
				.content(jsonString)).andDo(print()).andExpect(status().isCreated());

		// Store the savedProduct as the Product argument provided
		verify(productRepo,new Times(1)).save(captor.capture());
		Product savedProduct=captor.getValue();
		System.out.println(savedProduct);
		
		// Compare the expected to actual output
		assertEquals(product.getName(),savedProduct.getName());
		assertEquals(product.getId(),savedProduct.getId());
		assertEquals(product.getDescription(),savedProduct.getDescription()); 
		assertEquals(product.getPrice(),savedProduct.getPrice()); 
		assertEquals(product.getSellerId(),savedProduct.getSellerId()); 
		
	}
	
	@Test
	public void getProductByIdTest() throws Exception
	{
		// Building a product object
		Product product = buildProduct();
		
		// Getting a String representation of the product
		ObjectMapper map =new ObjectMapper();
		String jsonString = map.writeValueAsString(product);
		
		// Creating an Optional product of the product above i.e. isPresent()
		Optional<Product> optProd = Optional.of(product);
		
		/*
		 * When the findById method is run using the productRepo mock 
		 * Then the Optional product is returned
		 */
		when(productRepo.findById(any())).thenReturn(optProd);
		
		// The result is generated by performing a get request on the relevant endpoint
		MvcResult result = this.mockMvc.perform(get("/product/"+product.getId()).contentType(MediaType.APPLICATION_JSON))
		.andDo(print()).andExpect(status().isOk()).andReturn();
		
		// The body of the response is stored as a String
		String resultStr = result.getResponse().getContentAsString();

		// Compare the original expected jsonString with the newly created resultStr
		assertEquals(jsonString,resultStr);
	}
	
	public Product buildProduct()
	{
		Product product = new Product(1L, "Product 1", "Desc of Product 1", 25.0, 1L);
		return product;
	}

	
//	@Test
//	void contextLoads() {
//	}

}
